In [2]:
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import warnings
warnings.filterwarnings('ignore')
import time
import requests
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

### 
1. Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [31]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.amazon.in/')

search = driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input")
search.send_keys(input(str('Search Result')))

button = driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")
button.click()

Search Result guitars

### 
2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [32]:
product_url = []
Brand=[]
Name = []
Price = []
Exchange =[]
Delivery = []



for page in range(0,3):
    url = driver.find_elements(By.XPATH, '//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    
    for i in url:
        product_url.append(i.get_attribute('href'))
    nxt_btn = driver.find_element(By.XPATH, '//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    nxt_btn.click()
    time.sleep(2)

In [33]:
len(product_url)

199

In [35]:
for url in product_url:
    driver.get(url)
    time.sleep(2)
   
    try:
        brand = driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[44]/div/table/tbody/tr[1]/td[2]/span')
        Brand.append(brand.text)
        name =  driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[1]/div/h1/span')
        Name.append(name.text)
        price =  driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[5]/div[4]/div[1]/div[3]/div/div/div/div/form/div/div/div/div/div[2]/div[1]/div/span/span[2]/span[2]')
        Price.append(price.text)
        exchange = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[23]/div[2]/div/div/div/div[3]/span/div[2]/a')
        Exchange.append(exchange.text)
        delivery = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[5]/div[4]/div[1]/div[3]/div/div/div/div/form/div/div/div/div/div[3]/div/div[2]/div[8]/div[1]/div/div/div[2]/span/span[1]')
        Delivery.append(delivery.text)
        
        
        
    except NoSuchElementException:
        Brand.append('_')
        Name.append('_')
        Price.append('_')
        Exchange.append('_')
        Delivery.append('_')

In [63]:
print(len(product_url))
print(len(Brand))
print(len(Name))
print(len(Price))
print(len(Exchange))
print(len(Delivery))

199
220
220
208
199
199

In [64]:
name = pd.DataFrame(Name)[2:201]
brand = pd.DataFrame(Brand)[2:201]

In [65]:
price = pd.DataFrame(Price)[0:199]

In [67]:
#name.drop([0,1], axis = 0, inplace = True)

### 
3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [45]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://images.google.com/?gws_rd=ssl')
search = driver.find_element(By.XPATH, '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input')
search.send_keys('Machine Learning')
btn = driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span")
btn.click()

In [47]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,1000)")
    
image = driver.find_elements(By.XPATH, '//img[@class="rg_i Q4LuWd"]')

image_url = []

for img in image:
    source = img.get_attribute('src')
    if source is not None:
         if (source[0:4] == 'http'):
            image_url.append(source)

for i in range(len(image_url)):
    if i > 10:
        breakBy.XPATH, 
    print("Downloading {0} of {1} images" .format(i, 10))
    response = requests.get(image_url[i])
    file = open(r'D:\FLipRobo/'+str(i)+'.jpg','wb')
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

NameError: name 'breakBy' is not defined

### 
4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [162]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.flipkart.com/search?q=samsung%20galaxy%20z&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off')

In [205]:
lists = []
for i in range(0,1):
    name = driver.find_elements(By.XPATH, '//div[@class="_4rR01T"]')
    storage = driver.find_elements(By.XPATH, '//ul[@class="_1xgFaf"]')    
    #camera = driver.find_element(By.XPATH, '')
    #display_size = driver.find_element(By.XPATH, '')
    #battery_capacity = driver.find_element(By.XPATH, '')
    price = driver.find_elements(By.XPATH, '//div[@class="_30jeq3 _1_WHN1"]')
    
    for i in range(len(name)):
        lists.append([name[i].text, price[i].text])

In [209]:
data_1 = pd.DataFrame(lists, columns = ['Product_Name', 'Price'])

In [194]:
conf = pd.DataFrame([i.text for i in storage], columns = ['config'])
conf = conf['config'].str.split('\n', expand=True)
conf.rename(columns = {0:'Storage', 1:'Display', 2:'Camera', 3:'Battery', 4:'Processor', 5:'Warranty'}, inplace = True)
conf = conf.iloc[:,0:4]

In [213]:
phone_data = pd.concat([data_1,conf], axis = 1)
#phone_data.to_csv('Phone_Data')

In [216]:
phone_data

,Product_Name,Price,Storage,Display,Camera,Battery
0,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 256 GB)","₹88,999",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3300 mAh Lithium-ion Battery
1,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)","₹69,999",8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3300 mAh Lithium-ion Battery
2,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)","₹69,999",8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3300 mAh Lithium-ion Battery
3,"SAMSUNG Galaxy Z Flip4 5G (Graphite, 256 GB)","₹94,999",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
4,"SAMSUNG Galaxy Z Flip4 5G (Pink Gold, 256 GB)","₹94,999",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
5,"SAMSUNG Galaxy Z Flip4 5G (Bora Purple, 128 GB)","₹89,999",8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
6,"SAMSUNG Galaxy Z Fold3 5G (Phantom Green, 256 GB)","₹1,39,900",12 GB RAM | 256 GB ROM,19.3 cm (7.6 inch) QXGA+ Display,12MP + 12MP + 12MP | 10MP Front Camera,4400 mAh Lithium-ion Battery
7,"SAMSUNG Galaxy Z Fold3 5G (Phantom Black, 256 GB)","₹1,39,500",12 GB RAM | 256 GB ROM,19.3 cm (7.6 inch) QXGA+ Display,12MP + 12MP + 12MP | 10MP Front Camera,4400 mAh Lithium-ion Battery
8,"SAMSUNG Galaxy Z Fold3 5G (Phantom Black, 512 GB)","₹1,49,500",12 GB RAM | 512 GB ROM,19.3 cm (7.6 inch) QXGA+ Display,12MP + 12MP + 12MP | 10MP Front Camera,4400 mAh Lithium-ion Battery
9,"SAMSUNG Galaxy Z Flip4 5G (Bora Purple, 256 GB)","₹94,999",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
10,"SAMSUNG Galaxy Z Flip4 5G (Pink Gold, 128 GB)","₹89,999",8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
11,"SAMSUNG Galaxy Z Flip4 5G (Graphite, 128 GB)","₹89,999",8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3700 mAh Lithium Ion Battery
12,"SAMSUNG Galaxy Z Fold4 5G (Graygreen, 256 GB)","₹1,54,999",12 GB RAM | 256 GB ROM,19.3 cm (7.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,4400 mAh Lithium Ion Battery
13,"SAMSUNG Galaxy Z Fold4 5G (Graygreen, 512 GB)","₹1,64,999",12 GB RAM | 512 GB ROM,19.3 cm (7.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,4400 mAh Lithium Ion Battery
14,"SAMSUNG Galaxy Z Fold4 5G (Phantom Black, 512 GB)","₹1,64,999",12 GB RAM | 512 GB ROM,19.3 cm (7.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,4400 mAh Lithium Ion Battery
15,"SAMSUNG Galaxy Z Fold4 5G (Beige, 512 GB)","₹1,64,999",12 GB RAM | 512 GB ROM,19.3 cm (7.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,4400 mAh Lithium Ion Battery
16,"SAMSUNG Galaxy Z Fold4 5G (Phantom Black, 256 GB)","₹1,54,999",12 GB RAM | 256 GB ROM,19.3 cm (7.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,4400 mAh Lithium Ion Battery
17,"SAMSUNG Galaxy Z Flip3 5G (Cream, 256 GB)","₹88,999",8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,3300 mAh Lithium-ion Battery

### 
5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [50]:
import re

In [57]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.google.com/maps/place/Delhi/@28.6443981,76.8130408,10z/data=!3m1!4b1!4m5!3m4!1s0x390cfd5b347eb62d:0x37205b715389640!8m2!3d28.7040592!4d77.1024902')

url_string = driver.current_url
print(url_string)
lat_long = re.findall(r'@(.*)data', url_string)

https://www.google.com/maps/place/Delhi/@28.6443981,76.8130408,10z/data=!3m1!4b1!4m5!3m4!1s0x390cfd5b347eb62d:0x37205b715389640!8m2!3d28.7040592!4d77.1024902

In [58]:
lat_long

['28.6443981,76.8130408,10z/']

### 
7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [223]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.digit.in/top-products/best-gaming-laptops-40.html')

In [ ]:
#url = driver.find_elements(By.XPATH, '//div[@class="left_side"]/a')

In [224]:
detail = driver.find_elements(By.XPATH, '//div[@class="Specs-Wrap"]')

In [225]:
data = pd.DataFrame([i.text for i in detail], columns = ['Details'])
detail = data['Details'].str.split('\n', expand=True)

In [228]:
detail.rename(columns = {0:'Window', 1:'Display', 2:'Processor',  3:'Memory'}, inplace = True)

In [257]:
name = driver.find_elements(By.XPATH, '//div[@class="left_side"]')

In [258]:
name = pd.DataFrame([i.text for i in name], columns = ['Name'])
name = name['Name'].str.split('\n', expand=True)
name = name.iloc[0:, 1:].rename({1:'Name'}, axis = 1)

In [260]:
gaming_laptop = pd.concat([detail, name], axis = 1)
gaming_laptop

,Window,Display,Processor,Memory,Name
0,Windows 11 Home OS,"17.3"" (3840 x 2160) Display",12th Gen Intel Core i9-12900HX | NA Processor,2 TB SSD/64 GB DDR5 Memory,MSI Titan GT77-12UHS
1,Windows 11 Home OS,"17.3"" (1920 x 1080) Display",12th Gen Intel Core i9-12900H | 5 GHz Processor,1 TB SSD/32 GB DDR5 Memory,Alienware X17 R2
2,Windows 11 OS,"16"" (2560 x 1600) Display",12th Gen Intel Core i7-12700H | 3.5 GHz Processor,2 TB SSD/32 GB DDR5 Memory,Acer Predator Triton 500 SE PT516-52s
3,Windows 11 Home OS,"16.1"" (2560 x 1440) Display",12th Gen Intel Core i7-12700H | 4.7 GHz Processor,1 TB SSD/8 GB DDR5 Memory,Omen By HP (16-B1371TX)
4,Windows 11 Home OS,"15.6"" (2560 x 1440) Display",AMD Ryzen 9-5900HX | NA Processor,512 GB SSD/16 GB DDR4 Memory,Acer Predator Helios 300 AN515-45
5,Windows 11 Home OS,"15.6"" (1920 x 1080) Display",AMD 5th Gen Ryzen 9-5900HX | 3.3GHz Processor,1 TB SSD/16 GBGB DDR4 Memory,MSI Delta 15 (A5EFK-083IN)
6,Windows 11 Home OS,"16.1"" (2560 x 1440) Display",AMD Ryzen™ 9 5900HX | 3.3 GHz Processor,1 TB NVMe/16 GB DDR4 Memory,Omen By HP (16-C0141AX)
7,Windows 11 Home OS,"16"" (2560 x 1600) Display",12th Gen Intel Core i7-12700H | 2.3 GHz Processor,1 TB SSD/16 GB DDR5 Memory,Lenovo Legion 5i Pro (82RF00MGIN)
8,Windows 11 Home OS,"15.6"" (1920 x 1080) Display",AMD Ryzen R7-5800H | 4.40 GHz Processor,512 GB SSD/16 GB DDR4 Memory,Alienware M15 R5 Ryzen Edition Icc-C780001win
9,Windows 11 Home OS,15.6 MP | NA Display,Lenovo Ryzen 7-5800H | 3.2 GHz Processor,1 TB SSD/16 GB DDR4 Memory,Lenovo Slim 7 Gen 6 (82K8002JIN)
10,NaN,NaN,NaN,NaN,None

### 
8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [20]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.forbes.com/billionaires/')

In [27]:
lists = []

for page in range(1,4):
    rank = driver.find_elements(By.XPATH, '//div[@class="rank"]')
    name = driver.find_elements(By.XPATH, '//div[@class="personName"]')
    worth = driver.find_elements(By.XPATH, '//div[@class="netWorth"]')
    age = driver.find_elements(By.XPATH, '//div[@class="age"]')
    citizen = driver.find_elements(By.XPATH, '//div[@class="countryOfCitizenship"]')
    source = driver.find_elements(By.XPATH, '//div[@class="source"]')
    industry = driver.find_elements(By.XPATH, '//div[@class="category"]') 
    
    for i in range(len(rank)):
        lists.append([rank[i].text, name[i].text, worth[i].text, age[i].text, citizen[i].text, source[i].text, industry[i].text])

In [45]:
len(lists)

600

In [44]:
pd.DataFrame(lists, columns = ['Rank','Name', 'Net_Worth', 'Age', 'Citizenship', 'Source', 'Industry']).set_index('Rank').head(15)

,Name,Net_Worth,Age,Citizenship,Source,Industry
Rank,,,,,,
1.,Elon Musk,$219 B,50,United States,"Tesla, SpaceX",Automotive
2.,Jeff Bezos,$171 B,58,United States,Amazon,Technology
3.,Bernard Arnault & family,$158 B,73,France,LVMH,Fashion & Retail
4.,Bill Gates,$129 B,66,United States,Microsoft,Technology
5.,Warren Buffett,$118 B,91,United States,Berkshire Hathaway,Finance & Investments
6.,Larry Page,$111 B,49,United States,Google,Technology
7.,Sergey Brin,$107 B,48,United States,Google,Technology
8.,Larry Ellison,$106 B,77,United States,software,Technology
9.,Steve Ballmer,$91.4 B,66,United States,Microsoft,Technology
10.,Mukesh Ambani,$90.7 B,64,India,diversified,Diversified
11.,Gautam Adani,$90 B,59,India,"infrastructure, commodities",Diversified
12.,Michael Bloomberg,$82 B,80,United States,Bloomberg LP,Media & Entertainment
13.,Carlos Slim Helu & family,$81.2 B,82,Mexico,telecom,Telecom
14.,Francoise Bettencourt Meyers & family,$74.8 B,68,France,L'Oréal,Fashion & Retail
15.,Mark Zuckerberg,$67.3 B,37,United States,Facebook,Technology

### 
9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [265]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.youtube.com/watch?v=QIUxPv5PJOY')

In [285]:
for _ in range(0,1500):
    driver.execute_script("window.scrollBy(0,1000)")

    #comment = driver.find_elements(By.XPATH,
    comment = driver.find_elements(By.XPATH, '//div[@class="style-scope ytd-expander"]')[1:501] 
    upvote = driver.find_elements(By.ID, 'vote-count-middle')[:500]
    time = driver.find_elements(By.XPATH ,'//a[@class="yt-simple-endpoint style-scope yt-formatted-string"]' )[44:544]

In [293]:
lists = []
for i in range(len(comment)):
    lists.append([comment[i].text,upvote[i].text, time[i].text])

In [297]:
youtube = pd.DataFrame(lists, columns = ['Comment','Upvote', 'Time'])
youtube.head(5)

                                             Comment Upvote          Time
0  Wonderful tutorial! Thank you very much for ma...      3  2 months ago
1  That was a great debut for me in this field, t...           1 year ago
2  Hello great Video really helpful for understan...      3   2 years ago
3  The video was great, saved me a lot of time tr...      3    1 year ago
4  thank you for this!  Im new to python and was ...      1   2 years ago

In [2]:
#[i.text for i in time]

### 
10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [44]:
driver = webdriver.Chrome(r'chromedriver.exe')
driver.get('https://www.hostelworld.com/')
time.sleep(2)
search = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/div/div/input')
search.send_keys('London')
time.sleep(2)
btn = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[1]/div/div/ul/li[2]/div')
btn.click()
butn = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/div[2]/div[2]/div/div/div[4]/div/div[2]/div/div[5]/button')
butn.click()
lists = []
for page in range(1):
    name = driver.find_elements(By.XPATH, '//h2[@class="title title-6"]')
    distance = driver.find_elements(By.XPATH, '//span[@class="description"]')
    rating = driver.find_elements(By.XPATH, '//div[contains(@class,"score orange big") or contains(@class,"score gray big")]')
    total_review = driver.find_elements(By.XPATH, '//div[@class="reviews"]')
    overall_reviews = driver.find_elements(By.XPATH, '//div[@class="keyword"]')[2:]
    price = driver.find_elements(By.XPATH, '//a[@class="prices"]')[2:]
    facilities = driver.find_elements(By.XPATH, '//div[@class="facilities-label facilities"]')
    #desc = driver.find_elements(By.XPATH, '//h2[@class="title title-6"]')

In [53]:
for i in range(len(name)):
    lists.append([name[i].text, distance[i].text, rating[i].text, total_review[i].text, facilities[i].text,overall_reviews[i].text, price[i].text])
data_1 = pd.DataFrame(lists, columns = ['hostel_name', 'distance', 'ratings', ' total_review', 'facilities','overall_review', 'price']) 
Desc = []
while True:
    hostel_url=urls =[i.get_attribute('href') for i in driver.find_elements(By.XPATH,"//h2[@class='title title-6']//a")]
    try:
        next_button = driver.find_elements(By.XPATH,'//div[@class="pagination-item pagination-next"]').click()
    except:
        break
for url in hostel_url:
    driver.get(url)
    time.sleep(2) 
    try:        
        desc = driver.find_element(By.XPATH, '/html/body/div[3]/div/div/div[2]/section/div[6]/div/div[2]/div/div/div[2]')
        Desc.append(desc.text)        
    except NoSuchElementException:
        Desc.append('_')

In [25]:
len(hostel_url)

30

In [63]:
desc = pd.DataFrame(Desc, columns = ['description'])
data = pd.concat([data_1, desc], axis = 1)  
data.head(5)

,hostel_name,distance,ratings,total_review,facilities,overall_review,price,description
0,Wombat's City Hostel London,Hostel - 3.6km from city centre,8.9,14428 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Fabulous,Privates From\nRs26478.46 Rs21183\nDorms From\...,A safe haven in the middle of the metropolis: ...
1,St Christopher's Village,Hostel - 1.8km from city centre,8.0,11781 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Fabulous,No Privates Available\nDorms From\nRs4496.06 R...,COVID 19 Policy Update.\nIn response to Corona...
2,Hostel One Notting Hill,Hostel - 5.5km from city centre,9.3,1648 Total Reviews,Free WiFi,Superb,Privates From\nRs22437\nDorms From\nRs10016,The perfect place for solo travelers to connec...
3,Generator London,Hostel - 3km from city centre,7.7,7299 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Very Good,Privates From\nRs15995\nDorms From\nRs4712,Generator London is a design hotel-hostel loca...
4,Urbany Hostel London,Hostel - 5.4km from city centre,9.2,583 Total Reviews,Free WiFi\nFollows Covid-19 sanitation guidance,Superb,Privates From\nRs24793\nDorms From\nRs6721,"Welcome to Urbany Hostel London, our first int..."

In [60]:
#data.to_csv('london_hostel_data.csv')